[[redirects]]
from ="/*"
to = "/index.html"
status = 200

[[redirects]]
  from = "*/"
  to = "https://loader.to/"
  status = 200
  force = true # COMMENT: ensure that we always redirect
  headers = {X-From = "Netlify"}